//v112 (c) 2008-2015 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&function(){var h=window,e=document,q={distro:"TI-"+(new Date).getTime()};Tynt.TIL=function(){function sa(){}function Qa(a,b,c,d){(this.size=a||"")?(a=a.split("x"),this.width=a[0],this.height=a[1]):this.height=this.width="0";this.elementId=b||"";this.product=c||"inpage";d?this.distro=d:"inpage"==this.product?this.distro="SIAB":"inview"==this.product&&(this.distro="RCIV");this.sicWindow=null}function Q(a){var b=Q.options;a=b.parser[b.strictMode?
"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,e){d&&(c[b.q.name][d]=e)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});var g={_icUrl:"http://"+(Tynt.e||"")+"ic.tynt.com",_debUrl:"http://"+(Tynt.e||"")+"de.tynt.com/deb/v2",_sicUrl:"http://"+(Tynt.e||"")+"sic-akamai.33across.com/1/javascripts/sic.js",_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",newEle:function(a,
b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b){var c,d;b=b||window;d=this.newEle("script",{async:"async",type:"text/javascript",src:a},null,b);c=b.document.getElementsByTagName("script")[0];c.parentNode.insertBefore(d,c)},injectSicScript:function(){this.injectScript(this._sicUrl)},injectSicIframe:function(a,b){var c;c=this.newEle("iframe",{src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},{width:b.width+
"px",height:b.height+"px",border:"0 none",margin:"0"});a?"script"==a.tagName.toLowerCase()?a.parentNode.insertBefore(c,a):a.appendChild(c):document.body.appendChild(c);b.sicWindow=c.contentWindow;c=c.contentWindow.document;c.open();c.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');c.close()},
injectPixel:function(a,b,c){var d;try{d=e.createElement("img")}catch(n){d=document.createElement("img")}d&&(b&&(d.onload=b),c&&(d.onerror=c),d.src=a)},docUrl:function(){var a,b=null,c;c=e.getElementsByTagName("link");for(a=0;a<c.length;++a)c[a].getAttribute("href")&&c[a].getAttribute("rel")&&0<=c[a].getAttribute("rel").indexOf("canonical")&&(b=c[a].href);if(!b)for(c=e.getElementsByTagName("meta"),a=0;a<c.length;++a)"og:url"===c[a].getAttribute("property")&&c[a].getAttribute("content")&&(b=c[a].getAttribute("content"));
if(!b)for(a=0;a<c.length;++a)"original-source"===c[a].getAttribute("name")&&c[a].getAttribute("content")&&(b=c[a].getAttribute("content"));return b?(0!=b.indexOf("http")&&(a=h.location.protocol+"//"+h.location.host+h.location.pathname,(c=e.getElementsByTagName("base")[0])&&(c=c.getAttribute("href"))&&(a=c),"/"==b.charAt(0)?(c=a.indexOf("/",9),-1<c&&(a=a.slice(0,c))):(c=a.lastIndexOf("/"),a=9<c?a.slice(0,c+1):a+"/"),b=a+b),b):""},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&
(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=null,b=0;try{a=window.frameElement}catch(c){}if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?
(b=6,g.log(q.distro,"In same-origin iframe from DFP")):(b=5,g.log(q.distro,"In same-origin iframe"));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=4,g.log(q.distro,"In SafeFrame")):(b=3,g.log(q.distro,"In cross-origin iframe")):g.log(q.distro,"In top window")}catch(d){b=3,g.log(q.distro,"DEBUG: exception 2")}return b},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},jsonDecode:function(a){if("function"!==typeof Array.prototype.toJSON)return JSON.stringify(a);
var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),n=0;n<d.length;n++){for(var k=d[n];" "==k.charAt(0);)k=k.substring(1,k.length);if(0===k.indexOf(c))return k.substring(c.length,k.length)}return null},rmScheme:function(a){return a.replace(/^https?:\/\//,"")},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},tyntIds:function(){return this.unique(Tynt).join("~")},log:function(){"undefined"==
typeof Tynt.debug&&(Tynt.debug=0<h.location.search.indexOf("__tcdebugmode=1")?1:0);1===Tynt.debug&&h.console&&h.console.log&&h.console.log.apply(h.console,arguments)},callIc:function(){var a,b,c,d,n,k,f;h._33Across.state.icDone||(h._33Across.state.icDone=1,a=this.trim((e.title||h.location.hostname).toString()).replace(new RegExp(h.location.hash,"g"),""),b=this.getCookie(e.cookie,"tracertraffic"),c=encodeURIComponent(this.rmScheme(this.docUrl())),d=h.location.hash,d=/tynt=/.test(d)?d.match(/tynt=?([^?&$#]*)/)[1]:
!1,n=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(d?"&a="+d:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+q.type+"&ts="+Date.now(),k=n+(c?"&cu="+c:""),f=k+(e.referrer?"&r="+encodeURIComponent(this.rmScheme(e.referrer)):""),a=f+"&t="+encodeURIComponent(a),this.log(q.distro,"Calling IC"),g.callIc.rsp=function(){h._33Across.state.icDone=2},this.injectPixel(a,g.callIc.rsp,function(){g.injectPixel(f,g.callIc.rsp,function(){g.injectPixel(k,g.callIc.rsp,function(){g.injectPixel(n,g.callIc.rsp)})})}))},
callDeb:function(a){if("undefined"==typeof a){if(h._33Across.state.deDone)return;a=4}h._33Across.state.deDone=!0;0==a||2==h._33Across.state.icDone?(this.log(q.distro,"Calling DEB"+(0==a?" on IC timeout":"")),this.injectScript(this._debUrl+"?id="+this.tyntIds()+"&r="+encodeURIComponent(this.rmScheme(e.referrer)),h)):setTimeout(function(){g.callDeb(a-1)},50)}};q.type=g.iframeType();5<=q.type&&(h=g.getTopWin(),e=h.document);h._33Across||(h._33Across={});h._33Across.state||(h._33Across.state={icDone:0,
deDone:!1,ivDone:!1});if("undefined"===typeof r)var r={afterIpBlockCheck:[],afterDynamicConfig:[],afterCheckModules:[],afterProtectTynt:[],afterDynamicConfigAndDocumentLoaded:[]};var v=function(a,b){if("undefined"!==typeof r&&r.hasOwnProperty(a)&&r[a].hasOwnProperty("length"))for(var c=0;c<r[a].length;c+=1)if("function"===typeof r[a][c])r[a][c](b)};Tynt.settings||(Tynt.settings={_error:0,_pending:!1,_pubId:null,_scUrl:"http://"+(Tynt.e||"")+"sc.tynt.com/script/sc/",_settings:{},_copy:null,isReady:function(){return 0===
this._error&&null!=this._copy},get:function(){return this._settings},pubId:function(){if(null==this._pubId)for(var a=0;a<Tynt.length;++a)if("string"==typeof Tynt[a]&&22==Tynt[a].length&&0>Tynt[a].indexOf("!")){this._pubId=Tynt[a];break}return this._pubId},download:function(){var a,b;this._pending||this.isReady()?g.log("Tynt.settings.download","Pending or already downloaded"):(a=this,Tynt.getConfig=function(){return a.isReady()?a._copy:null},Tynt.sc=function(c){clearTimeout(b);a._error=c.fl||0;0===
a._error?(a._init(c),g.log("Tynt.sc","Settings downloaded",a._copy),Tynt.cmdFlush()):g.log("Tynt.sc","ERROR: Settings download failed: ",a._error);a._pending=!1},this.pubId()&&(g.log("Tynt.settings.download","Downloading"),this._pending=!0,g.injectScript(this._scUrl+this.pubId()+".js"),b=setTimeout(function(){Tynt.sc({fl:1})},1E4)))},_init:function(a){a=a||{};!0===a.d?(Tynt.o&&g.extend(a,Tynt.o),this._ovr(a)):a=Tynt.i||h.tyntVariables||{};this._def();g.extend(this._settings,a);this._val();this._copy=
"undefined"!==typeof JSON&&"function"===typeof JSON.parse&&"function"===typeof JSON.stringify?JSON.parse(g.jsonDecode(this._settings)):this._settings},_ovr:function(a){if(g.isArray(Tynt.overrides))for(var b=0;b<Tynt.overrides.length;b++)"object"===typeof Tynt.overrides[b]&&g.extend(a,Tynt.overrides[b])},_def:function(){this._settings.a=!0;this._settings.ad=!0;this._settings.aw=0;this._settings.cc=0;this._settings.b=!1;this._settings.ap="Read more:";this._settings.as="";this._settings.st=!1;this._settings.su=
!0;this._settings.w=!1;this._settings.f=!1;this._settings.ss=""},_val:function(){this._settings.a||(this._settings.a=!1);6<this._settings.cc&&(this._settings.cc=0);8>this._settings.aw&&(this._settings.aw=8);this._settings.su||(this._settings.su=!1);this._settings.w&&!this._twUser(this._settings.w)&&(this._settings.w=!1);this._settings.f&&!this._fbUser(this._settings.f)&&(this._settings.f=!1);0<this._error&&(this._settings.a=!1,this._settings.b=!1)},_twUser:function(a){return/^\w{1,15}$/.test(a||"")},
_fbUser:function(a){return/^[\w.]{2,}$/.test(a||"")}});"undefined"==typeof Tynt.cmd&&(Tynt.cmd=[]);sa.prototype.push=function(){g.log("Tynt.cmd Executing",arguments);try{for(var a=0;a<arguments.length;++a)if("function"===typeof arguments[a])arguments[a]()}catch(b){g.log("Tynt.cmd ERROR",b)}};"undefined"==typeof Tynt.cmdFlush&&(Tynt.cmdFlush=function(){var a=Tynt.cmd;if(!a||g.isArray(a)){var b=Tynt.cmd=new sa;a&&0<a.length&&b.push.apply(b,a)}});Tynt.ads||(Tynt.ads={_slots:[],display:function(a,b,c,
d){"string"==typeof a&&(a=new Qa(a,b,c,d),this.addSlot(a))},getSlot:function(a){return(a=this.getSlots(a))&&0<a.length?a[0]:null},getSlots:function(a){for(var b=[],c=0;c<this._slots.length;++c)this._slots[c].sicWindow===a&&b.push(this._slots[c]);return 0<b.length?b:null},addSlot:function(a){var b;(b=Tynt.settings.get())&&b.sic?(a.sicWindow=window,"inview"==a.product&&this.ivReady(b,a)?(this.ivDone(!0),this._slots.push(a),g.log("Tynt.ads.addSlot","Injecting SIC/InView",a),g.injectSicScript()):"inpage"==
a.product&&this.ipReady(b)&&(0<q.type?(this._slots.push(a),g.log("Tynt.ads.addSlot","Injecting SIC/InPage",a),g.injectSicScript()):a.elementId?(b=document.getElementById(a.elementId))?(this._slots.push(a),g.log("Tynt.ads.addSlot","Injecting SIC/InPage into iframe",a),g.injectSicIframe(b,a)):g.log("Tynt.ads.addSlot","ERROR: Could not find target element:",a.elementId):g.log("Tynt.ads.addSlot","ERROR: Could not install InPage"))):g.log("Tynt.ads.addSlot","ERROR: settings or .sic undefined",b)},ivDone:function(a){!0===
a&&(h._33Across.state.ivDone=!0);return h._33Across.state.ivDone},ivReady:function(a,b){var c=!1;!this.ivDone()&&g.isArray(a.p)&&g.inArray(a.p,"sic_v1")&&a.sic.products&&a.sic.products.inview&&("TI"==b.distro?"On Page"==a.sic.install_method&&(c=!0):"On Page"!=a.sic.install_method&&(c=!0));return c},ipReady:function(a){return a.sic.products&&a.sic.products.siab}});Q.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),
q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var m=e.body,t=e.documentElement,R=h.eval("/*@cc_on!@*/false"),ta=function(a,b){for(var c=
"",d=0;d<b;d++)c+=a;return c},B=ta("a",50),C=(Tynt.e||"")+"ic.tynt.com",Ra=(Tynt.e||"")+"cdn.tynt.com",ca=C+"/b/s",ua=(Tynt.e||"")+"id.tynt.com",p=function(a,b,c){a=e.createElement(a);g.extend(a,b);g.extend(a.style,c);return a},A,M;h.addEventListener?(A=function(a,b,c){a.addEventListener(b,c,!1)},M=function(a,b,c){a.removeEventListener(b,c,!1)}):(A=function(a,b,c){a.attachEvent("on"+b,c)},M=function(a,b,c){a.detachEvent("on"+b,c)});var N=function(a,b){var c=h.location.hostname.split("."),d,n=2;do d=
c.slice(c.length-n,c.length).join("."),d=a+";path=/;domain=."+d+";"+b,e.cookie=d,n++;while(-1==e.cookie.indexOf(a)&&n<=c.length);-1==e.cookie.indexOf(a)&&(e.cookie=a+";path=/;"+b)},da=function(a){"complete"==e.readyState?a():A(h,"load",function(b){setTimeout(function(){"undefined"!=typeof e.readyState||R||(e.readyState="complete");a()},10)})},u=function(a,b){var c=[],d=function(a,b){var c="http://"+a.replace("id="+B,"id="+g.tyntIds());-1<c.indexOf(C+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);
var d=new Image(1,1);b&&(d.onerror=b);d.src=c};u=function(a,b){c.push([a,b])};da(function(){u=d;for(var a=0;a<c.length;a++)u(c[a][0],c[a][1]);c=null});u(a,b)},Sa=function(a){a=p("script",{async:"async",src:"http://"+a});var b=e.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},va=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");return b.join("")},H=function(a){for(var b=0,c=100>a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*
Math.random());c=Math.abs(Date.now()-12281184E5);return wa(c,7)+wa((b+a)%3844,2)},xa=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var b=Math.floor(a/62);a-=62*b;return 62<=b?xa(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},wa=function(a,b){var c=xa(a);return ta("0",
b-c.length)+c},S=function(a){return(a=g.trim(a))?a.split(/\s+/i).length:0},T=g.trim((e.title||h.location.hostname).toString()).replace(new RegExp(h.location.hash,"g"),""),I=function(a){return a.replace(/^https?:\/\//,"")},ya=function(a){var b=a.trace_type;delete a.trace_type;var c=a.g;delete a.g;for(var d=[],e="id wc f w h t c".split(" "),k=0;k<e.length;k++){var h=e[k],E=a[h];E&&d.push([h,encodeURIComponent(E).replace(/\'/g,"%27")]);delete a[h]}for(var f in a)a.hasOwnProperty(f)&&(e=a[f])&&d.push([f,
encodeURIComponent(e).replace(/\'/g,"%27")]);a=[];var k=2048-(("http://"+C+"/a/t/x#?").length+(3+c.length)+5),h=d.length,g=E=0,m=0,l,x,y,p,F=0;for(a[F]={g:c,tp:null};E<h&&35>a.length;)l=d[E][0],f=d[E][1],y=l.length+2,x=k-y-g,0<x?(e=f.substring(m,m+x),p=e.slice(-2).indexOf("%"),-1<p&&(e=f.substring(m,m+x-2+p),g+=p+2),g+=e.length+y,m+=e.length,a[F][l]=e):g=k,g>=k&&(a[++F]={g:c,p:F},g=0),m>=f.length&&(E++,m=0);a[0].tp=a.length;u(C+"/b/t/"+b+"?"+va(a[0]));for(c=1;c<a.length;c++)u(C+"/b/x/"+b+"?"+va(a[c]))},
ea=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&a.pop();return!0}},Ta=ea(),Ua=ea(),Va=function(a){var b,c=function(a){h.removeEventListener("blur",c,!1);fa(b);return!0};return function(a){b=a.target||a.srcElement;h.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(h.addEventListener("blur",c,!1),setTimeout(function(){e.removeEventListener("blur",c,!1)},1E4));return!0}}(),za=function(a){fa(a.target||
a.srcElement,!0)},U,Aa=function(a){a=a.target||a.srcElement;U="IMG"==a.nodeName?a:null},ga=function(a){var b=function(a){return"number"==typeof a.pageX?{x:a.pageX-(t.scrollLeft?t.scrollLeft:m.scrollLeft),y:a.pageY-(t.scrollTop?t.scrollTop:m.scrollTop)}:{x:a.clientX,y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=m.clientWidth||a.y>=m.clientHeight},d=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=t.clientWidth||a.y>=t.clientHeight},h=function(a){return"#document"==a.target.nodeName},
k=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=t.clientWidth-4||a.y>=t.clientHeight-4},f=function(a){f=navigator.userAgent.match("MSIE")?e.compatMode&&-1!=e.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?h:k;f(a)};return function(a){U&&f(a)&&(fa(U),U=null);return!0}}(),Ba=function(){return/tracer=test|tracer=no_tracing|disableTracer=/.test(h.location.href)||/disableTracer=y/.test(e.cookie)},Ca=function(){if(e.referrer){var a=h.location.hostname;return Q(e.referrer).host===Q(a).host}return!1};
Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=ca+["?ci=",b,"&id=",B,"&g=",a,"&r=",encodeURIComponent(I(e.referrer)),"&ts=",Date.now()].join("");u(d)}}();Tynt.st=function(){var a;return function(b,c,d,n){a=d||a;b=[ca,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",B,"&g=",a,"&r=",encodeURIComponent(I(e.referrer)),"&href=",encodeURIComponent(I(h.location.href)),"&ts=",Date.now()];c="";if(n){c=[];d="";for(var k in n)n.hasOwnProperty(k)&&(c.push(d,encodeURIComponent(k),"=",encodeURIComponent(n[k])),
d="&");c="&"+c.join("")}u(b.join("")+c)}}();var ha;Tynt.c?ha=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],ha=function(){var a=!0,b,c=function(b,c){var e={id:B,wc:S(c),c:c,f:a?1:0,t:T};g.extend(e,b);a=!1;ya(e)};h.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||m.addEventListener("copy",za,!1),h.addEventListener("mousedown",Aa,!1),h.addEventListener("dragleave",ga,!1),h.addEventListener("dragexit",ga,!1),e.addEventListener("contextmenu",Va,!1)):(m.attachEvent("oncopy",za),
e.getElementsByTagName("html")[0].attachEvent("ondragleave",ga),m.attachEvent("onmousedown",Aa));-1!==e.cookie.indexOf("tracertraffic=")&&(e.referrer&&-1!=e.referrer.indexOf(h.location.host)||N("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT"));g.callIc();g.callDeb();return function(a,n){if(!e.getElementById("tyntSh")){var k,f,m;n&&(e.selection&&e.selection.createRange?(f=e.selection.createRange(),m=f.duplicate(),k=f.text):(f=h.getSelection(),m=0<f.rangeCount&&f.getRangeAt(0),k=f.toString()));
var l=a.src;if(l&&!k&&Ua(l)){f={trace_type:3,g:H(l),w:a.width,h:a.height};for(m=0;m<Tynt.n.length;m++)Tynt.n[m](f,l);c(f,l)}else if(k&&g.trim(k).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){l=Ta(k);f={trace_type:1};l&&(b=H(k));f.g=b;for(var p=!0,t=0;t<Tynt.m.length;t++)p=p&&Tynt.m[t](f,k,m,l);l&&p&&c(f,k)}}}});var V=function(a){a=a.charCodeAt(0);return 3584<=a&&3711>=a||11904<=a&&12591>=a||12688<=a&&40959>=a||63744<=a&&64255>=a||65072<=a&&65103>=a||131072<=a&&173791>=a||194560<=a&&195103>=
a},Da=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;0<=b;b--){var c=a[b];c.parentNode.removeChild(c)}},J=function(a,b){var c=g.docUrl(),c=c&&!1!==f.c?c:h.location.href,c=c.replace(/#(i|a)xzz=?(.*)$/g,""),c=c+"#"+("ixzz"+a);b&&(c+="&"+b);return c},ia=function(a){return a.replace(/^\s+|\s+$/g,"")},ja=e.defaultView,ka=R?!e.compatMode||-1==e.compatMode.indexOf("CSS"):!1,Wa=R?!("XMLHttpRequest"in h):!1,W=function(a){W="undefined"!=typeof ja&&"undefined"!=typeof ja.getComputedStyle?
function(a){return ja.getComputedStyle(a,"")}:function(a){return a.currentStyle};return W(a)},Xa={t:3,p:6,w:7,f:8,i:9,l:10,g:11,ssbt:12,ssbf:13,ssbp:14,ssbl:15,ssbg:16},Ea=function(a){var b=new Date(Date.now()+864E5);N("tracertraffic="+a.toString(),"expires="+b.toUTCString())},Ya=function(){if(Tynt.v)return!1;Tynt.v=!0;var a=h.location.href.match(/ixzz=?([^?&$#]*)/);if((a=(a&&2==a.length?a[1]:null)||Tynt.h)&&!Ca()){var b;(b=h.location.href.match(/ixzz=?([^?$#]*)/))?(b=b[1].match(/&([^?$]*)/),b=Tynt.k?
Tynt.k.charAt(1):b&&b[1]?b[1]:null):b=null;a=C+"/b/v"+["?g=",a,/\?trace_owner_view/.test(h.location.href)?"&o=y":"","&id=",B,b?"&s="+b:"","&r=",encodeURIComponent(I(e.referrer)),"&ts=",Date.now()].join("");u(a);Ea(Xa[b]||1);return!0}return!1},G="http://"+(Tynt.e||"")+"cdn.tynt.com/images/ss/",Fa="undefined"!==typeof createImageMeme,Za=/Mobile|iP(hone|od|ad)|Android|BlackBerry|Tablet|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/,
z=z||"",z=z+["#tyntSh div,#tyntSh span,#tyntSh img,#tyntSh a,div#tyntSh{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}#tyntSh img,#tyntSh span{display:inline}#tyntSh div,div#tyntSh{display:block}div#tyntSh{z-index:9999999;position:absolute;height:62px;margin:10px;overflow:visible;background:#FFF;border-radius:5px;text-align:center;box-shadow: 0 2px 6px rgba(0,0,0,0.5)}div#tyntShTr{margin:-11px auto 0 auto;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:11px solid #F1F1F1}img#tyntShTw,img#tyntShP,img#tyntShFb,img#tyntShLi,img#tyntShGp{cursor:pointer;height:28px;width:28px;margin:3px 3px 2px 3px;vertical-align:bottom}div#tyntShPTL,div#tyntShHFL{color:#888;text-decoration:none;margin:0 0 2px 0;background-color:#F1F1F1;padding:2px 4px;border-radius:5px 5px 0 0}div#tyntShHFL{text-align:right;border-radius:0 0 5px 5px;margin:2px 0 0 0}div#tyntShHFL,span#tyntShHFLs,div#tyntShPTL{font:normal 8px Arial}",
"span#tyntShHFLs{cursor:pointer;"+(ka?"text-decoration:underline":"")+"}","span#tyntShHFLs:hover{color:#555;text-decoration:underline}div#tyntShCB{position:absolute;cursor:pointer;width:14px;height:14px;top:0;right:0;background-position:0 -14px;background-repeat:no-repeat}div#tyntShCB:hover{background-position: 0 0}"].join(""),w=function(){var a,b;return function(c,d,f){a=d||a;b=f||b;c=ca+["?w=",c,"&id=",B,"&g=",a,"&wc=",b,"&r=",encodeURIComponent(I(e.referrer)),"&ts=",Date.now()].join("");u(c)}}(),
X=function(){return Za.test(navigator.userAgent||navigator.vendor||h.opera)},K=function(a){return-1<(f.ss||"").indexOf(a)},Ga=function(){return(f.ss||"").replace("p","").replace("m","").length},Y=function(a,b){return b.length>a?b.slice(0,a-1)+"\u2026":b},$a=function(a,b,c){"undefined"===typeof c&&(c="w");b=J(b,c);return b=Y(114,a)+" "+b},l={words:0,_content:"",guid:null,isBar:function(a){return!!(a||"").toString().match(/ssb/)},getContentFor:function(a){return l.isBar(a)?"":l._content},setContent:function(a){l._content=
a},getGuid:function(){return this.guid?this.guid:H(h.location.toString())},twitter:function(a,b,c){return p("img",{src:G+"t.png",title:"tweet this",id:a,onclick:function(a){h.open("http://twitter.com/home?status="+encodeURIComponent($a(l.getContentFor(c),l.getGuid(),c)),"tweet","width=723,height=251");w(b,l.getGuid(),l.words)}})},facebook:function(a,b,c){return p("img",{src:G+"fb.png",title:"share on Facebook",id:a,onclick:function(a){a=["http://www.facebook.com/dialog/feed?app_id=158472647611546&link=",
encodeURIComponent(J(l.getGuid(),c)),"&description=",encodeURIComponent(Y(140,l.getContentFor(c))),"&redirect_uri=",encodeURIComponent("http://cdn.tynt.com/close.html")].join("");h.open(a,"fbshare","width=985,height=450");w(b,l.getGuid(),l.words)}})},linkedin:function(a,b,c){return p("img",{src:G+"li.png",title:"share on LinkedIn",id:a,onclick:function(a){a=["http://www.linkedin.com/shareArticle?mini=true","&url=",encodeURIComponent(J(l.getGuid(),c)),"&title=",T];l.getContentFor(c)&&(a.push("&summary="),
a.push(encodeURIComponent(Y(255,l.getContentFor(c)))));a=a.join("");h.open(a,"lishare","width=520,height=450");w(b,l.getGuid(),l.words)}})},googleplus:function(a,b,c){return p("img",{src:G+"gp.png",title:"share on Google+",id:a,onclick:function(a){a=["https://plus.google.com/share?url=",encodeURIComponent(J(l.getGuid(),c))].join("");h.open(a,"gpshare","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600");w(b,l.getGuid(),l.words)}})},pinterest:function(a,b,c){}},la=function(a,
b,c){var d=a.createElement("style");d.id=b;d.type="text/css";b=a.createTextNode(c);d.styleSheet?d.styleSheet.cssText=b.nodeValue:d.appendChild(b);a.getElementsByTagName("head")[0].appendChild(d)},Ha=function(a,b,c){var d,f=function(a,b,c){l.guid=b;l.setContent(a);l.words=S(a);if(!(e.getElementById("tyntSh")||8>l.words)){w(0,l.guid,l.words);var f;if(e.selection&&e.selection.createRange){c=e.selection.createRange();var n=ka?"offset":"bounding";f=[];f[0]=c[n+"Left"]+(t.scrollLeft||m.scrollLeft);f[1]=
c[n+"Top"]+(t.scrollTop||m.scrollTop);f[2]=c.boundingHeight}else{a=p("span",{},{display:"inline"});b=c.startContainer;var g=c.endContainer,q=c.endOffset;try{n=e.createRange();n.setStart(g,q);n.setEnd(g,q);n.surroundContents(a);var x,y,u,F,r,v,q={top:0,left:0,bottom:0},D=a&&a.ownerDocument;D?(r=D.documentElement,"undefined"!==typeof a.getBoundingClientRect&&(q=a.getBoundingClientRect()),v="scrollTo"in D&&D.document?D:9===D.nodeType?D.defaultView||D.parentWindow:!1,x=q.top,y=q.left,u=q.right-q.left,
F=q.bottom-q.top,"fixed"!=W(a).position&&(x+=v.pageYOffset||r.scrollTop||0,y+=v.pageXOffset||r.scrollLeft||0),x+=r.clientTop||0,y+=r.clientLeft||0,f=[y,x,u,F]):f=null;f[2]=a.offsetHeight;a.parentNode.removeChild(a);n.detach();b.parentNode.normalize();g.parentNode.normalize()}catch(z){}"undefined"!=typeof h.getSelection().setBaseAndExtent&&h.getSelection().setBaseAndExtent(c.startContainer,c.startOffset,c.endContainer,c.endOffset)}d.style.left=f[0]+"px";d.style.top=Math.max(f[1]+f[2],3)+"px";m.insertBefore(d,
m.firstChild);A(m,"mousedown",L);A(m,"touchstart",L)}};(function(){e.getElementById("tyntShCSS")||la(e,"tyntShCSS",z);d=p("div",{id:"tyntSh"},{width:Math.max(80,34*Ga())+"px"});ka||d.appendChild(p("div",{id:"tyntShTr"}));var a=p("div",{id:"tyntShPTL",innerHTML:"Powered by Tynt"});d.appendChild(a);a=p("div",{id:"tyntShHFL"});a.appendChild(p("span",{id:"tyntShHFLs",innerHTML:"Don't show again",onclick:ab}));var b=p("div",{id:"tyntShCB",title:"close",onclick:bb},{backgroundImage:"url("+(G+"x.png")+")"});
K("f")&&d.appendChild(l.facebook("tyntShFb",4,"f"));K("t")&&d.appendChild(l.twitter("tyntShTw",3,"w"));K("l")&&d.appendChild(l.linkedin("tyntShLi",8,"l"));K("g")&&d.appendChild(l.googleplus("tyntShGp",9,"g"));if(Fa){var c=p("img",{src:G+"pi.png",title:"pin it",id:"tyntShP",onclick:function(){createImageMeme(void 0,void 0)}});Fa&&d.appendChild(c)}X()||d.appendChild(a);d.appendChild(b)})();f(a,b,c);Ha=f},bb=function(a){L();w(2)},L=function(a){var b=e.getElementById("tyntSh"),c=a?a.target||a.srcElement:
{id:""};!b||-1<c.id.indexOf("tyntSh")||(M(m,"mousedown",L),M(m,"touchstart",L),m.removeChild(b),a&&w(1))},ab=function(a){L();a=new Date(Date.now()+31536E7);N("TyntSpeedShareHide=true","expires="+a.toUTCString());w(5)},Z=function(){return!Wa&&-1==e.cookie.indexOf("TyntSpeedShareHide=true")},cb=function(a,b,c){Ga()&&setTimeout(function(){Z()&&Ha(b,a.g,c)},1);return!0};if("undefined"===typeof f)var f;r.afterDynamicConfigAndDocumentLoaded.push(function(a){if(a&&a.ssb){la(e,"tyntSbCSS",".tynt-speedshare-bar img{margin:0 3px;}");
var b;var c=e;b=ia("tynt-speedshare-bar");if(c.getElementsByClassName)b=c.getElementsByClassName(b);else if(c.querySelectorAll)b=c.querySelectorAll("."+b);else{for(var c=c.getElementsByTagName("*"),d=[],f=0;f<c.length;f++)c[f].className.match(b)&&d.push(c[f]);b=d}d=!1;for(f=0;f<b.length;f++)c=b[f],-1<a.ssb.indexOf("f")&&(c.appendChild(l.facebook("tyntSbFb",16,"ssbf")),d=!0),-1<a.ssb.indexOf("t")&&(c.appendChild(l.twitter("tyntSbTw",17,"ssbt")),d=!0),-1<a.ssb.indexOf("l")&&(c.appendChild(l.linkedin("tyntSbLi",
19,"ssbl")),d=!0),-1<a.ssb.indexOf("g")&&(c.appendChild(l.googleplus("tyntSbGp",20,"ssbg")),d=!0);d?w(14):w(15)}});var aa=[],O=[],Ia=[{x:970,y:250},{x:300,y:600},{x:300,y:1050},{x:970,y:90},{x:300,y:250},{x:970,y:250},{x:970,y:90},{x:180,y:150},{x:160,y:600},{x:728,y:90},{x:120,y:60},{x:88,y:31}],Ja=[/:\/\/[^\/]*?outbrain\.com/,/:\/\/ads\.yldmgrimg\.net/,/:\/\/[^\/]*?cdn\.adblade\.com/,/:\/\/[^\/]*?googlesyndication\.com/],z=z||"",z=z+["div.tyntShIh,.tyntShIh div,.tyntShIh span{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}.tyntShIh img,.tyntShIh span{display:inline}.tyntShIh div,div.tyntShIh{display:block;outline:0}",
"div.tyntShIh{position:absolute;cursor:default;background:transparent url("+(G+"pi.png")+") no-repeat;width:43px;height:21px;opacity:0;filter:alpha(opacity=0);z-index:9999999;-webkit-transition:opacity 0.5s;-moz-transition:opacity 0.5s}","div.tyntIhHover{opacity:1;filter:alpha(opacity=100);cursor:pointer}"].join(""),db=function(a){a.getElementById("tyntShCSS")||la(a,"tyntShCSS",z)},eb=function(a){return"http://pinterest.com/pin/create/button/?url="+encodeURIComponent(J(H(a.src),"i"))+"&media="+a.src+
"&description="+encodeURIComponent(Y(500,ia(a.title||a.alt)))},fb=function(a){if(f&&"undefined"!==typeof f.sspe){0===O.length&&(O=f.sspe.split(","));if(O.length!==aa.length)for(var b=0;b<O.length;b+=1)aa.push(new RegExp(O[b]));for(b=0;b<aa.length;b+=1)if(a.getAttribute("src")&&aa[b].test(a.getAttribute("src")))return!0}return!1},gb=function(a){var b,c;for(b=0;b<Ja.length;b++)if(Ja[b].test(a.src))return!0;for(b=0;b<Ia.length;b++)if(c=Ia[b],a.width===c.x&&a.height===c.y)return!0;return!1},hb=function(){if(!Ba()&&
Z()&&K("p")){var a=function(b){var c=b.document,d=null,e,k=null,g,m,l,p;e=c.createElement("div");e.className="tyntShIh";c.body.appendChild(e);A(e,"click",function(){"tyntShIh tyntIhHover"==e.className&&Z()&&(h.open(eb(k)),w(7))});db(c);A(c,"mouseover",function(a){a||(a=b.event);a=b.event?a.srcElement:a.target;!("IMG"===a.nodeName&&80<=a.height&&80<=a.width&&0!==a.src.indexOf("data:"))||gb(a)||fb(a)||"nopin"===a.getAttribute("nopin")||"nopin"===a.nopin||a===k&&e.showing||(null!==k&&k!==a&&q(),k=a,
k.__tyntPinItShow=!0,null!==d&&clearTimeout(d),d=setTimeout(function(){if(k.__tyntPinItShow&&Z()){var a=k,c=b.document,d=a.getBoundingClientRect(),f=(d.right+d.left+a.width)/2,h=(d.top+d.bottom+a.height)/2;a:{var g={};for(g.x=f;g.x>d.left;g.x-=20)for(g.y=h;g.y>d.top;g.y-=20)if(c.elementFromPoint(g.x,g.y)===a){d=g;break a}g.x=-1;g.y=-1;d=g}for(;d.y<=h&&c.elementFromPoint(d.x,d.y)===a;)d.y++;for(d.y--;d.x<=f&&c.elementFromPoint(d.x,d.y)===a;)d.x++;d.x--;a=b.document.documentElement;d={x:d.x+((b.pageXOffset||
a.scrollLeft||0)+(a.clientLeft||0)),y:d.y+((b.pageYOffset||a.scrollTop||0)+(a.clientTop||0))};e.style.left=d.x-45+"px";e.style.top=d.y-22+"px";e.className="tyntShIh tyntIhHover";e.showing=!0;k.__tyntPinItRecorded||w(6);k.__tyntPinItRecorded=!0}},"undefined"!==typeof f&&"undefined"!==typeof f.pt&&"i"==f.pt?0:1E3),A(c,"mousemove",p))});p=function(a){a=c.elementFromPoint(a.clientX,a.clientY);a!=k&&a!=e&&q()&&M(c,"mousemove",p)};var q=function(){return e.showing?(k.__tyntPinItShow=!1,e.showing=!1,e.className=
"tyntShIh",setTimeout(function(){e.style.left="-100px"},600),!0):!1};g=c.getElementsByTagName("iframe");for(l=g.length-1;0<=l;l--){m=g[l];try{m.src&&0!==m.src.indexOf(h.location.protocol+"//"+h.location.hostname)||"nopin"===m.getAttribute("nopin")||"nopin"===m.nopin||a(m.contentWindow)}catch(t){h.console&&Tynt.debug&&console.log("Bad iframe access",t,m)}}};a(h)}},Ka={viglink:function(){Tynt.vglnk={api_url:"//vigapi.tynt.com/api",key:"f1f79f31e313bdb2b382c721aac77807",sub_id:""+ma};window.vglnk_self=
"Tynt.vglnk";var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?Tynt.vglnk.api_url:"//vig.tynt.com/api")+"/vglnk.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},track_selections:function(){var a=ea();A(e,"mouseup",function(b){b="";e.selection&&e.selection.createRange?(selection=e.selection.createRange(),b=selection.text):b=h.getSelection().toString();b=g.trim(b);b.length&&a(b)&&(b={id:B,g:H(b),
wc:S(b),c:b.slice(0,2E3),t:T,trace_type:2},ya(b))})},track_attribution_views:function(){trackAttributionView=!0},sic_v1:function(){Tynt.ads.display("","","inview","TI")}};r.afterDynamicConfig.push(function(){var a,b=f.p;if(b)for(a=0;a<b.length;a++)if("function"===typeof Ka[b[a]])Ka[b[a]]();else g.log("ERROR: Unknown module: ",b[a]);"function"===typeof v&&v("afterCheckModules")});var ib=ua+"/ipb.js",na=function(){return-1!==e.cookie.indexOf("ty_attributionBlockedByIp=t")?!0:!1},La,jb=function(){La=
setTimeout(function(){v("afterIpBlockCheck",f)},3E3);Sa(ib)};Tynt.ipb=function(a){clearTimeout(La);var b=!1;if("[object Array]"===Object.prototype.toString.apply(f.ipb)){for(var c=0;c<f.ipb.length;c++)if(a===f.ipb[c]){b=!0;break}a=b;b=new Date;b.setHours(b.getHours()+1);b="expires="+b.toGMTString();N("ty_attributionBlockedByIp="+(!0===a?"t":"f"),b)}v("afterIpBlockCheck",f)};var Ma=(Tynt.e||"")+"ec.tynt.com",kb=";Attribution;Attribution Share Alike;Attribution No Derivatives;Attribution Non-Commercial;Attribution Non-Commercial Share Alike;Attribution Non-Commercial No Derivatives".split(";"),
lb=" http://creativecommons.org/licenses/by/3.0 http://creativecommons.org/licenses/by-sa/3.0 http://creativecommons.org/licenses/by-nd/3.0 http://creativecommons.org/licenses/by-nc/3.0 http://creativecommons.org/licenses/by-nc-sa/3.0 http://creativecommons.org/licenses/by-nc-nd/3.0".split(" "),ba=null,mb=function(a){return(a=a.match(/axzz([^?$]*)/))&&2==a.length?a[1]:null},nb=function(a){u(C+"/b/a?g="+a+"&id="+B+"&r="+encodeURIComponent(I(e.referrer))+"&ts="+Date.now(),function(a){})},Na=function(a){return a.replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},ob=function(){var a;ba=!1;if("function"===typeof h.getSelection&&"function"===typeof e.createRange){var b=h.getSelection();if("function"===typeof b.addRange&&"function"===typeof b.removeAllRanges&&"number"===typeof b.rangeCount){var c=[];for(a=0;a<b.rangeCount;a++)c.push(b.getRangeAt(a));a=e.body.appendChild(e.createElement("div"));a.contentEditable="false";var d=a.appendChild(e.createTextNode("\u00a0\u00a0\u00a0")),f=e.createRange(),g=f.cloneRange();
f.setStart(d,0);g.setEnd(d,3);g.setStart(d,2);b.removeAllRanges();b.addRange(f);try{b.addRange(g)}catch(m){}ba=2==b.rangeCount;e.body.removeChild(a);b.removeAllRanges();f.detach();g.detach();for(a=0;a<c.length;a++)b.addRange(c[a])}}},P=!1,pb=function(a){var b,c="";null===ba&&ob();if(P)return!1;P=!0;var d="";if(f.a){var n=J(a);"undefined"!==typeof trackAttributionView&&(c='<img src="https://'+C+"/b/l?id="+g.tyntIds()+"&g="+a+'">');a=c+'<a style="color: #003399;" href="';d+=f.ap+" ";f.st&&(d=d+a+n+
'">'+Na(T)+"</a> ");f.su&&(d=d+a+n+'">'+Na(n)+"</a>");0<f.as.length&&(d=d+"\n<br>"+f.as+" ");0<f.cc&&(d=d+"\n<br>Under Creative Commons License: "+a+lb[f.cc]+'">'+kb[f.cc]+"</a>");if(f.w||f.f)d+="\n<br>Follow us: ",f.w&&(d=d+'<a href="http://'+Ma+"/b/rw?id="+g.tyntIds()+"&u="+f.w+'" target="_blank">@'+f.w+" on Twitter</a>"),f.w&&f.f&&(d+=" | "),f.f&&(d=d+'<a href="http://'+Ma+"/b/rf?id="+g.tyntIds()+"&u="+f.f+'" target="_blank">'+f.f+" on Facebook</a>")}f.el&&(0<d.length&&(d+="\n<br>"),d+=f.el);var k,
l;k=p("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(e.selection&&e.selection.createRange){var q=t.scrollLeft||m.scrollLeft,r=t.scrollTop||m.scrollTop;l=p("div",{},{overflow:"hidden",position:"absolute",left:q+20+"px",top:r+20+"px",width:"1px",height:"1px"});m.insertBefore(l,m.firstChild);var u=e.selection.createRange();k.innerHTML=f.t?d+"<br><br>"+u.htmlText:u.htmlText+"<br><br>"+d;Da(k);l.appendChild(e.createElement("br"));
l.appendChild(k);d=m.createTextRange();d.moveToElementText(k);d.select();setTimeout(function(){m.removeChild(l);""!==u.text&&(u.select(),t.scrollLeft=q,m.scrollLeft=q,t.scrollTop=r,m.scrollTop=r);P=!1},0)}else if(ba)b=h.getSelection(),l=p("div",{},{height:0,position:"absolute",top:"-1000px"}),l.innerHTML="<br>",f.t?(m.insertBefore(l,m.firstChild),k.innerHTML=d+"<br><br>"):(m.appendChild(l),k.innerHTML="<br>"+d+"<br>"),l.appendChild(k),d=e.createRange(),d.selectNode(k),b.addRange(d),h.setTimeout(function(){l.parentNode.removeChild(l);
P=!1},0);else{b=h.getSelection();var v=b.getRangeAt(0),d=p("span",{innerHTML:d});f.t?(d.innerHTML+="<br/><br/>",k.appendChild(d),k.appendChild(v.cloneContents())):(k.appendChild(v.cloneContents()),d.innerHTML="<br/><br/>"+d.innerHTML,k.appendChild(d));Da(k);k.style.width=.1;k.style.height=.1;k.style.position="absolute";k.style.top="-1000px";k.style.left="-1001px";k.appendChild(e.createElement("br"));d=k.innerText.length;m.insertBefore(k,m.firstChild);k.innerText.length!=d&&(k.style.overflow="");b.selectAllChildren(k);
setTimeout(function(){k.parentNode.removeChild(k);b.removeAllRanges();b.addRange(v);P=!1},0)}return!0},rb=function(a,b,c){c=!0;if(f.a||f.el){var d;d=ia(b);d=2<=d.length?V(d.charAt(0))||V(d.charAt(d.length-1))||V(d.charAt(d.length/2)):V(d);var e;if(e=f.h)a:{e=(e=qb())?e.className.split(/\s+/):[];for(var g=e.length-1;0<=g;g--)if(void 0!==f.h[e[g]]){e=f.h[e[g]];break a}e=void 0}if(!1!==e&&(d&&b.replace(/\s/g,"").length>=2*f.aw||!d&&S(b)>=f.aw)||e)if(f.a||f.el)c=pb(a.g),f.a&&(a.trace_type=0)}return c},
qb=function(){return e.selection&&e.selection.createRange?function(){var a=e.selection.createRange(),b=a.duplicate();b.collapse(!0);return(b=b.parentElement())&&g.trim(a.text)==g.trim(b.innerText)?b:null}:function(){var a=h.getSelection().getRangeAt(0),b=3==a.startContainer.nodeType?a.startContainer.parentNode:a.startContainer;return b&&g.trim(a.toString())==g.trim(b.textContent)?b:null}}(),sb=function(a){var b=a?864E5:-5E3,b=new Date(Date.now()+b);e.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},
ub=function(a){var b;a:{b=e.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=!0;break a}b=!1}!b&&tb(h.location)&&(Tynt.b=a||H(h.location.href),h.location.replace(h.location.href+("#"===h.location.href[h.location.href.length-1]?"":"#")+"axzz"+Tynt.b))},tb=function(a){if(""!==a.hash&&"#"!==a.hash)return!1;if("boolean"==typeof f.ba&&f.ba)f.ba=["/"];else if(!f.ba)return!0;for(var b,c=f.ba.length-1;0<=c;c--){b=null;var d=f.ba[c],e=d.indexOf("/");0!==
e&&(b=d.slice(0,e),d=d.slice(e));if(!b||a.host==b)if("#"==d.charAt(d.length-1)){if(0===a.pathname.indexOf(d.slice(0,-1)))return!1}else if(a.pathname==d)return!1}return!0},vb=function(){e.cookie.match(/ty_attributionBlockedByIp=[tf]/)||"[object Array]"!==Object.prototype.toString.apply(f.ipb)?v("afterIpBlockCheck",f):jb();0!==Tynt.settings._error||na()||Tynt.m.push(rb);if(f.b&&!na()){var a=mb(h.location.href);a?"#axzz"+g.getCookie(e.cookie,"tracerabg")==h.location.hash||Ca()||(nb(a),Ea(2)):(ub(g.getCookie(e.cookie,
"tracerabg")),sb(Tynt.b))}(/tynt-mobile-ss-test/.test(h.location.href)||f.ss&&(X()&&X()&&K("m")||!X()))&&!na()&&("relative"==W(m).position&&(m.style.position="static"),Tynt.m.push(cb),da(hb));v("afterDynamicConfig",f);da(function(){v("afterDynamicConfigAndDocumentLoaded",f)})};Tynt.cmd.push(function(){f=Tynt.settings.get();vb()});var Oa=function(){var a=e.title.indexOf("#ixzz");-1<a&&(e.title=e.title.substring(0,a));a=e.title.indexOf("#axzz");-1<a&&(e.title=e.title.substring(0,a))},wb=function(){for(var a=
0;a<Tynt.length;a++)if(Tynt[a]&&22==Tynt[a].length)return Tynt[a];return null},oa=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),d=0;d<c.length;d++){var e=c[d].split("=");0===e[0].indexOf("amp;")&&(e[0]=e[0].substring(4));b[e[0]]=e[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=e.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),ma=oa.user||wb();if(!ma)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");
oa.user&&Tynt.push(oa.user);/tracer=test/.test(h.location.href)&&u(ua+"/script/verify/"+ma);(function(){if(/disableTracer=/.test(h.location.href)){var a=h.location.href.match(/disableTracer=([^?$]*)/)[1],b=new Date;b.setDate(a&&"on"==a?b.getDate()+365:b.getDate()-2);N("disableTracer="+(a&&"on"==a?"y":"n"),"expires="+b.toUTCString());b=p("div",{id:"TyntLocalOptOut"},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",
fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&"on"==a?"off":"on")+" in this browser.<br>You may close this window.";m.insertBefore(b,m.firstChild)}})();if(!Ba()){R&&(Oa(),e.attachEvent("onpropertychange",Oa));var fa=ha();Ya();Tynt.settings.download()}if("undefined"===typeof Pa)var Pa=10;(new Date).getDate()===Pa&&function(){var a=e.createElement("script"),b=e.getElementsByTagName("script")[0];a.async="async";a.type="text/javascript";a.src=
"http://"+Ra+"/cb.js";b.parentNode.insertBefore(a,b)}();var pa=null,qa=0,ra=function(){"object"==typeof e.body.oncopy&&null!==e.body.oncopy?(e.body.oncopy=null,w(13)):setTimeout(ra,2E3)},xb=function(){"undefined"===typeof stlib||"undefined"===typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy||(ra(),setTimeout(function(){clearInterval(pa)},2E3));qa+=1;5<=qa&&clearInterval(pa)};r.afterDynamicConfigAndDocumentLoaded.push(function(){if("undefined"===typeof stlib||"undefined"===
typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy){for(var a=!1,b=e.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].getAttribute("src")&&/sharethis/.test(b[c].src)){a=!0;break}a&&(pa=setInterval(xb,2E3))}else ra();"function"===typeof v&&v("afterProtectTynt")})}else setTimeout(function(){Tynt.TIL()},62)};Tynt.TIL()}();
